### ISSUE TITLE
Suggestion: clear chat window when set to don't scroll when send message is pressed

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#111]
The don't scroll works fine but it shows the start of new content often below the visible area. 

When not scroll is set when I press "Send message" I would expect the new text to start from the top. Similar to ctrl+L (clear) on a Linux commandline followed by sending the message. 

We do want to be able to scroll back to previous output though.

**Comment by AntonKrug** [comment]
I will look at it after resolving the other ticket

**Comment by AntonKrug** [comment]
I was thinking about it and could this be matter of preference? Imagine use case "i want the scrolling to NOT change at all when i click don't scrool, that's why i'm clicking it" imagine you have lot of text and you scrolled back to something you liked and suddenly you realized that you want to ask something new and you do not want to lose `your current possition`, you click the `don't scroll` and what it does, instantly the opposite, it does scroll down.

So this might be matter of taste?

**Comment by AntonKrug** [comment]
Another problem is that when content is empty, it start on the top as there is nothing else to render, when content is bigger than 1 screen you get the scroll, but from that point you can only scroll within the content, the last line will be always on bottom. For example even this GH webpage, the fotter is on the bottom of the webpage, that's the end, you can't scroll past that and certanly you can't scroll past the footer so much that you would make it apear on the top of the webpage.

This wouldn't be just about scrolling or not, this would be adding artificial padding in the content just to have enough content so it would apear on top, and then various problem, what we will do if the user resizes the window.

@rjmacarthy are you sure you want this to be attempted?

**Comment by rjmacarthy** [comment]
I agree and I think we should leave it as it is, it's too complicated to implement and a matter of preference as you say.
