### ISSUE TITLE
Ollama app not starting automatically

### ISSUE THREAD

**Issue by LeonardoGentile** [rjmacarthy/twinny#38]
Hello, 
thank you very much for this plugin! It works correctly in my case but I have a minor problem as mentioned in this other issue: https://github.com/jmorganca/ollama/issues/2031#issuecomment-1899309093

Basically, I don't want Ollama to be running on my system all the times, so when I've installed it I might have disable the "run in background" or "run at login", I can't recall which one. I've now enabled again "run in background" but it didn't solve the problem I'm about to explain.

I've realized that when Ollama.app is not running and I launch vscode then the Ollama.app icon bounces a couple of times on the dock meaning it's being launched (probably by this plugin) but I can't see anything on the menubar.

The only way is to manually click on the Ollama.app icon, then everything works again (but I have to re-launch vscode if it was already running). 

My question: is this plugin trying to launch Ollama.app when lauching/restarting vscode? If so why can't it start the server? Can it be an access rights problem?

**Comment by rjmacarthy** [comment]
Hello @LeonardoGentile thanks for reporting the issue.

This plugin executes `ollama serve` using `child_process` `exec` when you open vscode and the plugin is enabled.

I guess the problem could be that if ollama is already running then it tries anyway, I am not sure why it causes Ollama.app to run as I am not familiar with it.

Maybe a check to see if it's running first before attempting to start it would fix the issue here.

Feel free to open a PR if you're comfortable or I will update it in a future release.

Many thanks

**Comment by LeonardoGentile** [comment]
Hello @rjmacarthy, thanks for your answer.
But the thing is that even if it's not running, the plugin _tries_ to launch ollama, it just can't. 
As I mentioned, I can see the app bouncing but the server is not started anyway

**Comment by rjmacarthy** [comment]
Hey @LeonardoGentile thanks for your reply.  

I have added an option in the settings menu now `Disable Server Checks` which stops all the checks at the beginning when the extension runs.  I'm confused as to why it doesn't work for you because the `child_process` should return without an error for `ollama --version` and `ollama list`  to indicate Ollama is installed.  

Regardless, if you enable this option the checks will be skipped and no messages will appear.

Many thanks,

**Comment by rjmacarthy** [comment]
I'm disabling the auto setup of Ollama in twinny because we now support many more providers so this issue should be fixed in the latest version once it's released `3.5.16`.
