### ISSUE TITLE
No sponsor ship button on your profile page

### ISSUE THREAD

**Issue by AntonKrug** [rjmacarthy/twinny#61]
**Is your feature request related to a problem? Please describe.**
I would like to sponsor your account with $1 a month (like some other GH users have)

**Describe the solution you'd like**
If you would enable sponsorship with with a $1 tier, i could join it

**Describe alternatives you've considered**
One off paypal, revolut could work too

**Comment by rjmacarthy** [comment]
Hello @AntonKrug,

First and foremost, I'm touched by your kind offer to support this project. It means a lot.

To make things easier, I've added a sponsor button directly on the repository's home page. I chose this method over setting up a profile sponsorship because it's more straightforward and quicker to implement.

Please know that any contribution you decide to make is much appreciated, and I'm grateful for your generosity. Additionally. your interest in and support of this work is already incredibly valuable without monetary donations.

Thank you so much for considering to support this work.

Many thanks
