### ISSUE TITLE
Ollama utilising 100% of GPU and freezing on M1 Pro and Max

### ISSUE THREAD

**Issue by petercherm** [rjmacarthy/twinny#97]
Hi, I tried running Twinny on two different laptops (one with M1 Pro and the other one with M1 Max), and while chat seems to be working ok, I can't get the autocomplete to work. As soon as I start typing, the Ollama process sucks up 100% of the GPU and freezes. It makes the fans spin like crazy after a few moments, and even if I close the VSCode and Ollama app, it keeps utilising 100% of the GPU until I kill the Ollama process in the activity monitor. Has anyone experienced similar behaviour?

**Comment by brunoais** [comment]
This seems to be completely unrelated to twinny. I'd raise this to ollama instead.

I've noticed that too already but I'm still trying to reproduce without being by mistake.

**Comment by rjmacarthy** [comment]
Hey @petercherm please can you let us know which model you are trying to use for FIM?

**Comment by petercherm** [comment]
@rjmacarthy I'm using the default `codellama:7b-code` model. I tried downloading it manually and through `Twinny`, but no luck.

**Comment by petercherm** [comment]
I searched Ollama issues on GitHub, but I can't see anything similar to what I'm experiencing.

**Comment by rjmacarthy** [comment]
What happens if you try `ollama run codellama:7b-code '<PRE> def compute_gcd(x, y): <SUF>return result <MID>'` in your terminal?

**Comment by petercherm** [comment]
> What happens if you try `ollama run codellama:7b-code '<PRE> def compute_gcd(x, y): <SUF>return result <MID>'` in your terminal?

It works as expected:

```
% ollama run codellama:7b-code '<PRE> def compute_gcd(x, y): <SUF>return result <MID>'

  if x == 0:
    return y
  else:
    return compute_gcd(y % x, x)

def compute_lcm(a, b):
  result = (a * b) // compute_gcd(a, b)
   <EOT>
```

**Comment by rjmacarthy** [comment]
Hmm seems it's working properly, it means that the extension "should" work properly too...Sometimes I have to stop the ollama service and then start it again as it seems to hang randomly.  

Saying that: on a Macbook you might have better luck with the `deepseek` models which are less intensive on memory e.g `deepseek-coder:6.7b-base-q5_K_M`.

The last thing I can suggest is checking the `resolve` method in `completion.ts` to see if it's handling `\n` (line breaks) properly, this is what is used to determine whether or not to destroy the stream, it could be that it's not recognising them and streaming in the background more completions.  Specifically in the code below it will break on end of the stream, when max lines is reached or if single line, after the first line break.

https://github.com/rjmacarthy/twinny/blob/d4f30fb1c4b555ca4e3ff2c18cea1631557abaa6/src/providers/completion.ts#L246

If you could help debug that on your macbook that would be helpful because I am using only Linux here to use/write this extension.

Many thanks,

**Comment by petercherm** [comment]
@rjmacarthy I have 64GB RAM on this machine; I don't think it's a memory issue. I will try another model as you suggested. I'm also happy to have a look at the `completion.ts`  later today. I'll keep you updated with my findings.

**Comment by petercherm** [comment]
I briefly debugged `completion.ts` and noticed it sometimes throws the following error in the debugging console:

```
Error: socket hang up
	at connResetException (/Users/petercherm/git/other/twinny/lib/internal/errors.js:720:14)
	at Socket.socketCloseListener (/Users/petercherm/git/other/twinny/lib/_http_client.js:474:25)
	at Socket.emit (/Users/petercherm/git/other/twinny/lib/events.js:526:35)
	at TCP.<anonymous> (/Users/petercherm/git/other/twinny/lib/net.js:323:12)
	at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {code: 'ECONNRESET', stack: 'Error: socket hang up
	at connResetException …Trampoline (node:internal/async_hooks:130:17)', message: 'socket hang up'}
```

Not very helpful...

**Comment by rjmacarthy** [comment]
I've noticed that a few times, I found it's hard to track down the cause of it...Generally though it doesn't happen for me much at all now.

**Comment by rjmacarthy** [comment]
Hey, I added logging and removed some logic which might cause socket hangup in the latest version.  

Hope it helps.

Many thanks,

**Comment by rjmacarthy** [comment]
Stale
